jeecg:
  route:
    config:
      #type:database nacos yml
      data-type: database
      data-id: jeecg-gateway-router
spring:
  data:
    redis:
      database: ${REDIS_DB:0}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PWD:}
knife4j:
  production: false