logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR
    
spring:
  profiles:
    active: '@profile.name@'
  application:
    name: jeecg-system
  main:
    allow-circular-references: true
  config:
    import:
      - optional:nacos:${spring.application.name}-@profile.name@.yaml
      - optional:classpath:config/application-liteflow.yml
  cloud:
    nacos:
      config:
        server-addr: @config.server-addr@
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        group: @config.group@
        namespace: @config.namespace@
        username: @config.username@
        password: @config.password@